# Generated by Django 5.1.4 on 2024-12-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to='banners/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
