# Generated by Django 5.1.4 on 2024-12-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_advertisement_expiration_date_category_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='expiration_date',
        ),
    ]
