# Generated by Django 5.1.4 on 2024-12-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_advertisement_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
